### ISSUE TITLE
Does not seem to work as intended.

### ISSUE THREAD

**Issue by jukefr** [ndabAP/vue-go-example#5]
When on the heroku demo page :
1. Generate a new data set
2. Click stats calculation button once => get 1st results.
3. Click stats calculation button 2nd time => get 2nd results
4. Click stats calculation button N times => get N results
(same for distribution curve, I get a new one at every button click)

tl;dr Calculations do not seem to use the "currently generated" data set.

edit: seems to get worse the more points you have generated.

**Comment by ndabAP** [comment]
Good catch. I guess it's because in-memory storage and if another user changes the random data, you get his results.
